// Private object storage for borrower documents.
//
// Two drivers behind one tiny interface:
//   - LocalDiskStorage  — development / single-host fallback (DOCUMENTS_DIR, git-ignored)
//   - SupabaseStorage   — production: a PRIVATE Supabase Storage bucket, server-side uploads
//                         with the service-role key (never in the browser), objects fetched
//                         by the server and handed to Flo through the authenticated connector.
//
// Why Supabase Storage: it is already part of this stack (the site's Login goes to a
// Supabase-backed app and a Supabase connector is attached to the workspace), it gives a
// private bucket with no public URLs, signed-URL access when we want it, per-object
// metadata, and simple deletion — without adding a cloud account. See
// DOCUMENT_UPLOAD_IMPLEMENTATION.md.
//
// Keys are generated by the server (see documentStore.js) and validated here: no path
// traversal, no absolute paths, no odd characters.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_DIR = path.resolve(HERE, '..', 'data', 'documents');
const KEY_RE = /^[a-z0-9][a-z0-9_\-./]{3,240}$/;

export function assertSafeKey(key) {
  if (typeof key !== 'string' || !KEY_RE.test(key) || key.includes('..') || key.includes('//') || key.startsWith('/')) {
    throw new Error('unsafe storage key');
  }
  return key;
}

export class LocalDiskStorage {
  constructor(dir = process.env.DOCUMENTS_DIR || DEFAULT_DIR) {
    this.dir = dir;
    this.kind = 'local';
    fs.mkdirSync(dir, { recursive: true });
  }

  _file(key) {
    assertSafeKey(key);
    const file = path.resolve(this.dir, key);
    if (!file.startsWith(path.resolve(this.dir) + path.sep)) throw new Error('unsafe storage key');
    return file;
  }

  async put(key, buffer, _mimeType) {
    const file = this._file(key);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.tmp`;
    fs.writeFileSync(tmp, buffer, { mode: 0o600 });
    fs.renameSync(tmp, file);
    return { key };
  }

  async get(key) {
    return fs.readFileSync(this._file(key));
  }

  async exists(key) {
    return fs.existsSync(this._file(key));
  }

  async delete(key) {
    const file = this._file(key);
    if (fs.existsSync(file)) fs.unlinkSync(file);
  }

  /** Local storage has no signed URLs; the authenticated internal fetch endpoint is the access path. */
  async signedUrl() {
    return null;
  }
}

export class SupabaseStorage {
  constructor({ url = process.env.SUPABASE_URL, serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY, bucket = process.env.SUPABASE_STORAGE_BUCKET || 'loan-documents', fetchImpl = globalThis.fetch } = {}) {
    if (!url || !serviceKey) throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for Supabase storage');
    this.base = `${url.replace(/\/+$/, '')}/storage/v1`;
    this.headers = { Authorization: `Bearer ${serviceKey}`, apikey: serviceKey };
    this.bucket = bucket;
    this.fetch = fetchImpl;
    this.kind = 'supabase';
  }

  _objectUrl(key) {
    return `${this.base}/object/${encodeURIComponent(this.bucket)}/${assertSafeKey(key).split('/').map(encodeURIComponent).join('/')}`;
  }

  async put(key, buffer, mimeType) {
    const res = await this.fetch(this._objectUrl(key), {
      method: 'POST',
      headers: { ...this.headers, 'Content-Type': mimeType || 'application/octet-stream', 'x-upsert': 'false', 'cache-control': 'private, max-age=0' },
      body: buffer,
    });
    if (res.status === 409) return { key, existed: true };
    if (!res.ok) throw new Error(`storage upload failed (${res.status})`);
    return { key };
  }

  async get(key) {
    const res = await this.fetch(this._objectUrl(key), { headers: this.headers });
    if (!res.ok) throw new Error(`storage download failed (${res.status})`);
    return Buffer.from(await res.arrayBuffer());
  }

  async exists(key) {
    const res = await this.fetch(this._objectUrl(key), { method: 'HEAD', headers: this.headers });
    return res.ok;
  }

  async delete(key) {
    const res = await this.fetch(this._objectUrl(key), { method: 'DELETE', headers: this.headers });
    if (!res.ok && res.status !== 404) throw new Error(`storage delete failed (${res.status})`);
  }

  /** Short-lived signed URL (private bucket) — used only for Ashley-side previews if ever needed. */
  async signedUrl(key, expiresInSeconds = 300) {
    const res = await this.fetch(`${this.base}/object/sign/${encodeURIComponent(this.bucket)}/${assertSafeKey(key).split('/').map(encodeURIComponent).join('/')}`, {
      method: 'POST',
      headers: { ...this.headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({ expiresIn: expiresInSeconds }),
    });
    if (!res.ok) throw new Error(`storage sign failed (${res.status})`);
    const body = await res.json();
    return body.signedURL ? `${this.base}${body.signedURL}` : null;
  }
}

export function createDocumentStorage(env = process.env) {
  if ((env.DOCUMENT_STORAGE || '').toLowerCase() === 'supabase' || (env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY)) {
    return new SupabaseStorage({ url: env.SUPABASE_URL, serviceKey: env.SUPABASE_SERVICE_ROLE_KEY, bucket: env.SUPABASE_STORAGE_BUCKET });
  }
  return new LocalDiskStorage(env.DOCUMENTS_DIR);
}
